name = "phoenix-wolf-systems-worker"
type = "javascript"
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true
route = ""
zone_id = "${CF_ZONE_ID}"

[vars]
ADMIN_HANDLE = "Keli"
SETUP_TOKEN = "${CF_SETUP_TOKEN}"

[[kv_namespaces]]
binding = "SECRETS_KV"
id = "${CF_KV_SECRETS_ID}"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "${CF_KV_SESSIONS_ID}"

[[kv_namespaces]]
binding = "AUDIT_KV"
id = "${CF_KV_AUDIT_ID}"
